title: Mark Lester A. Samson 
image_url: "https://raw.githubusercontent.com/Fiorehisui/SamsonResume/1f9a897c69ef86e491980e2448adfa02641d59d9/mark%20(2).jpg"
text: Marklestersans@gmail.com
theme: jekyll-theme-minimal
